name: tree-nn
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - networkx
  - tskit
  - msprime
  - stdpopsim
  - snakemake=7
  - jupyter
  - notebook
  - pip
  - r-base
  - r-essentials
  - bcftools
  - tabix
  - scikit-learn
  - theano
  - tensorflow
  - keras
  - pytorch
  - jax
  - numba
